spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/codechella_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-docs-ui
    enabled: true
